openapi: 3.0.1
info:
  title: coreAccounting
  description: >-
    This is a generated connector for [WorkDay Connect Service REST API
    v1](https://community.workday.com/sites/default/files/file-hosting/restapi/index.html)
    OpenAPI specification.

    The Core Accounting service enables applications to access and configure
    common financial components that you use to manage your financial
    accounting.
  version: v1
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 

    Follow [this guide] https://credentials.workday.com/docs/authentication/ and
    obtain tokens.
  x-ballerina-display:
    label: Workday coreAccounting
    iconPath: icon.png
tags:
  - name: currencies
    description: Provides the ability to retrieve information on currencies in your tenant.
  - name: evaluateAccountPostingRules
    description: >-
      Retrieves the ledger account and resulting worktags of an account posting
      rule with specified parameters. To reduce performance impact to your
      tenant, Workday recommends that you use parallel calls for your
      integration and ensure that the parameters you specify are unique.
paths:
  /currencies:
    get:
      tags:
        - currencies
      summary: Retrieves the details on all currencies in your tenant.
      operationId: getAllCurrencies
      description: >-
        Retrieves the details on all currencies in your tenant. Workday
        retrieves the:

        * ID

        * Descriptor

        * Precision

        * Code


        Secured by: Core Navigation


        Scope: Adaptive Planning for the Workforce, Adaptive Planning for
        Financial Plans
      responses:
        '200':
          description: >-
            Successful response. A successful response can return no matched
            data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: >-
                        #/components/schemas/CurrencySummary
                  total:
                    type: integer
                    format: int64
                description: collection something or other
        '400':
          description: Invalid request. (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '401':
          description: >-
            Invalid resource or operation.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '403':
          description: >-
            User has insufficient permissions.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '404':
          description: >-
            Resource not found.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_MODEL_REFERENCE'
  /currencies/{id}:
    get:
      tags:
        - currencies
      summary: Retrieves the details of a specified currency.
      operationId: getCurrencyByID
      description: >-
        Retrieves the details of a specified currency. Workday retrieves the:

        * ID

        * Descriptor

        * Precision

        * Code


        Secured by: Core Navigation


        Scope: Adaptive Planning for the Workforce, Adaptive Planning for
        Financial Plans
      parameters:
        - name: id
          in: path
          description: The Workday ID of the resource.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            Successful response. A successful response can return no matched
            data.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/CurrencySummary
        '400':
          description: Invalid request. (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '401':
          description: >-
            Invalid resource or operation.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '403':
          description: >-
            User has insufficient permissions.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '404':
          description: >-
            Resource not found.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_MODEL_REFERENCE'
  /evaluateAccountPostingRules:
    get:
      tags:
        - evaluateAccountPostingRules
      summary: >-
        Retrieves the ledger account and resulting worktags of a specified
        account posting rule.
      operationId: getLedgerAccountByPostingRule
      description: >-
        Retrieves the ledger account and resulting worktags of an account
        posting rule with specified parameters.


        Secured by: Set Up: Accounting Rules


        Scope: Common Financial Management
      parameters:
        - name: accountPostingRuleSet
          in: query
          description: >-
            (Required) The Workday ID or reference ID for the account posting
            rule set. The reference ID uses the
            accountPostingRuleSet=sampleRefIdType=value format. Example:
            accountPostingRuleSet=Account_Posting_Rule_Set_ID=ACCOUNT_POSTING_RULE_SET-1
          schema:
            type: string
        - name: accountPostingRuleType
          in: query
          description: >-
            (Required) The Workday ID or reference ID for the account posting
            rule type. The reference ID uses the
            accountPostingRuleType=sampleRefIdType=value format. Example:
            accountPostingRuleType=Account_Posting_Rule_Type_ID=CASH
          schema:
            type: string
        - name: dimensionValue
          in: query
          description: >-
            The Workday IDs or reference IDs for the dimension value of the
            account posting rule condition. The reference ID uses the
            dimensionValue=sampleRefIdType=value format format. Example:
            dimensionValue=Fund_ID=F03.1.3.
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: >-
            Successful response. A successful response can return no matched
            data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: >-
                        #/components/schemas/ViewLedgerAccount
                  total:
                    type: integer
                    format: int64
                description: collection something or other
        '400':
          description: Invalid request. (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '401':
          description: >-
            Invalid resource or operation.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '403':
          description: >-
            User has insufficient permissions.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        '404':
          description: >-
            Resource not found.
            (https://community.workday.com/rest/error-messages)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VALIDATION_ERROR_MODEL_REFERENCE'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_MODEL_REFERENCE'
components:
  schemas:
    INSTANCE_MODEL_REFERENCE:
      required:
        - id
      type: object
      properties:
        id:
          pattern: ^(?:(?:[0-9a-f]{32})|(?:[0-9]+\$[0-9]+)|(\S+=\S+))$
          type: string
          description: wid / id / reference id
        descriptor:
          type: string
          description: A description of the instance
          readOnly: true
        href:
          type: string
          description: A link to the instance
          readOnly: true
    ERROR_MODEL_REFERENCE:
      required:
        - error
      type: object
      properties:
        error:
          type: string
          description: A description of the error
    VALIDATION_ERROR_MODEL_REFERENCE:
      allOf:
        - $ref: '#/components/schemas/ERROR_MODEL_REFERENCE'
        - type: object
          properties:
            errors:
              type: array
              description: An array of validation errors
              items:
                $ref: '#/components/schemas/ERROR_MODEL_REFERENCE'
    MULTIPLE_INSTANCE_MODEL_REFERENCE:
      type: object
      properties:
        total:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/INSTANCE_MODEL_REFERENCE'
    ViewLedgerAccount:
      allOf:
        - type: object
          properties:
            ledgerAccountName:
              type: string
              description: The name of the ledger account.
              example: '1050: Cash'
              x-workday-type: Text
            resultingWorktags:
              type: array
              description: The resulting worktags configured for an account posting rule.
              items:
                $ref: >-
                  #/components/schemas/WorkTagSummary
              x-workday-type: Multi-instance
            descriptor:
              type: string
              description: A preview of the instance
              example: Lorem ipsum dolor sit ame
            id:
              type: string
              description: Id of the instance
    CurrencySummary:
      allOf:
        - type: object
          properties:
            code:
              type: string
              description: ID
              example: >-
                Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut,
                ubique iisque contentiones ex duo. Quo lorem etiam eu.
              x-workday-type: Text
            precision:
              type: integer
              description: Precision
              example: 5
              x-workday-type: Numeric
            descriptor:
              type: string
              description: A preview of the instance
              example: Lorem ipsum dolor sit ame
            id:
              type: string
              description: Id of the instance
    WorkTagSummary:
      allOf:
        - type: object
          properties:
            descriptor:
              type: string
              description: A preview of the instance
              example: Lorem ipsum dolor sit ame
            id:
              type: string
              description: Id of the instance
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://tenantauthorizationhostname
          scopes: {}
