openapi: 3.0.1
info:
  title: Magento B2B AddressDetail
  version: 2.2.10
  description: >-
    This is a generated connector for [Magento REST API v2.2](https://devdocs.magento.com/guides/v2.4/rest/bk-rest.html) OpenAPI specification.

    The Magento B2B Rest API service enables applications to build and manage a customized commerce store. 
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 
 
    Follow [this guide](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html) and obtain tokens.
  x-ballerina-display:
    label: Magento Amazon billing address & analytics
    iconPath: "icon.png"
tags:
  - name: addresses/{addressId}
  - name: amazon-billing-address/{amazonOrderReferenceId}
  - name: amazon-shipping-address/{amazonOrderReferenceId}
  - name: amazon/order-ref
  - name: analytics/link
security:
  - bearerAuth: []
paths:
  /V1/addresses/{addressId}:
    delete:
      tags:
        - addresses/{addressId}
      summary: Delete customer address by ID.
      description: Delete customer address by ID.
      operationId: customerAddressDeleteByIdV1
      parameters:
        - name: addressId
          in: path
          required: true
          description: Address ID
          schema:
            type: integer
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                type: boolean
                description: true on success
            application/xml:
              schema:
                type: boolean
                description: true on success
        '400':
          description: 400 Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
  /V1/amazon-billing-address/{amazonOrderReferenceId}:
    put:
      tags:
        - amazon-billing-address/{amazonOrderReferenceId}
      summary: Update Amazon-billing-address by ID
      operationId: updateAmazonPaymentAddressV1
      parameters:
        - name: amazonOrderReferenceId
          in: path
          required: true
          schema:
            type: string
          description: Amazon order reference ID
      requestBody:
        description: Address Consent Token
        content:
          application/json:
            schema:
              required:
                - addressConsentToken
              type: object
              description: Address Consent Token
              properties:
                addressConsentToken:
                  type: string
                  description: Address Consent Token
              xml:
                name: request
          application/xml:
            schema:
              required:
                - addressConsentToken
              description: Address Consent Token(XML)
              type: object
              properties:
                addressConsentToken:
                  description: Address Consent Token
                  type: string
              xml:
                name: request
        required: false
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
      x-codegen-request-body-name: amazonPaymentAddressManagementV1GetBillingAddressPutBody
  /V1/amazon-shipping-address/{amazonOrderReferenceId}:
    put:
      tags:
        - amazon-shipping-address/{amazonOrderReferenceId}
      summary: Update amazon-shipping-address by reference ID
      operationId: updateAmazonPaymentShippingAddress
      parameters:
        - name: amazonOrderReferenceId
          description: Amazon Order Reference ID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Address consent token
        content:
          application/json:
            schema:
              required:
                - addressConsentToken
              type: object
              description: Address Consent Token (JSON)
              properties:
                addressConsentToken:
                  description: Address Consent Token
                  type: string
              xml:
                name: request
          application/xml:
            schema:
              required:
                - addressConsentToken
              type: object
              description: Address Consent Token (XML)
              properties:
                addressConsentToken:
                  description: Address Consent Token
                  type: string
              xml:
                name: request
        required: false
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
      x-codegen-request-body-name: AmazonPaymentShippingAddressDetail
  /V1/amazon/order-ref:
    delete:
      tags:
        - amazon/order-ref
      summary: amazon/order-ref
      operationId: DeleteAmazonPaymentOrderReferenceV1
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
  /V1/analytics/link:
    get:
      tags:
        - analytics/link
      summary: analytics/link
      operationId: getAnalyticsLinkV1
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/analytics-data-link-interface'
            application/xml:
              schema:
                $ref: '#/components/schemas/analytics-data-link-interface'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
            application/xml:
              schema:
                $ref: '#/components/schemas/error-response'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    analytics-data-link-interface:
      required:
        - initialization_vector
        - url
      type: object
      properties:
        url:
          type: string
          description: URL
        initialization_vector:
          description: initialization vector
          type: string
      description: >-
        Interface LinkInterface Represents link with collected data and
        initialized vector for decryption.
    error-response:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          $ref: '#/components/schemas/error-errors'
        code:
          type: integer
          description: Error code
        parameters:
          $ref: '#/components/schemas/error-parameters'
        trace:
          type: string
          description: Stack trace
    error-errors:
      type: array
      description: Errors list
      items:
        $ref: '#/components/schemas/error-errors-item'
    error-errors-item:
      type: object
      properties:
        message:
          type: string
          description: Error message
        parameters:
          $ref: '#/components/schemas/error-parameters'
      description: Error details
    error-parameters:
      type: array
      description: Error parameters list
      items:
        $ref: '#/components/schemas/error-parameters-item'
    error-parameters-item:
      type: object
      properties:
        resources:
          type: string
          description: ACL resource
        fieldName:
          type: string
          description: Missing or invalid field name
        fieldValue:
          type: string
          description: Incorrect field value
      description: Error parameters item
x-tagGroups:
  - name: addresses
    tags:
      - addresses/{addressId}
  - name: amazon billing address
    tags:
      - amazon-billing-address/{amazonOrderReferenceId}
  - name: amazon shipping address
    tags:
      - amazon-shipping-address/{amazonOrderReferenceId}
  - name: amazon
    tags:
      - amazon/order-ref
  - name: analytics
    tags:
      - analytics/link
