#!/usr/bin/env bash
# Creates the OpenAPI update pull request with retry logic.
# Expects BRANCH_NAME env var set by the calling workflow step.
# Writes PR_NUMBER to GITHUB_ENV.
set -euo pipefail

UPDATED_LIST=$(jq -r '.updated[] | "- \(.name) (\(.vendor)/\(.apiId)@\(.version))"' UPDATE_SUMMARY.json 2>/dev/null || echo "")
MALFORMED_LIST=$(jq -r '.malformed[] | "- \(.name) v\(.version): \(.reason)"' UPDATE_SUMMARY.json 2>/dev/null || echo "")
UPDATED_COUNT=$(jq '.updated | length' UPDATE_SUMMARY.json 2>/dev/null || echo "0")
MALFORMED_COUNT=$(jq '.malformed | length' UPDATE_SUMMARY.json 2>/dev/null || echo "0")

{
    echo "## OpenAPI Specification Updates"
    echo ""
    echo "This PR contains automated updates detected by the Dependabot monitor."
    echo ""
    echo "### Changes ($UPDATED_COUNT updated, $MALFORMED_COUNT malformed):"
    echo "$UPDATED_LIST"
    if [ -n "$MALFORMED_LIST" ]; then
        echo ""
        echo "Malformed specs (found but not downloaded):"
        echo "$MALFORMED_LIST"
    fi
    echo ""
    echo "### Structure:"
    echo "All specifications follow the standard structure:"
    echo "- openapi/{vendor}/{api}/{version}/openapi.json"
    echo "- openapi/{vendor}/{api}/{version}/.metadata.json"
    echo ""
    echo "### Checklist:"
    echo "- Review specification changes"
    echo "- Verify connector generation works"
    echo "- Run tests"
    echo "- Update documentation if needed"
    echo ""
    echo "This PR was automatically generated by the OpenAPI Dependabot"
} > /tmp/pr_body.md

PR_TITLE="[Dependabot] chore: Update OpenAPI Specifications - $(date +%Y-%m-%d)"

# Check first in case the PR was created but the error response swallowed the URL.
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number' 2>/dev/null || echo "")
if [ -n "$EXISTING_PR" ]; then
    echo "PR already exists: #$EXISTING_PR"
    PR_NUMBER="$EXISTING_PR"
else
    MAX_RETRIES=3
    RETRY_COUNT=0
    PR_NUMBER=""
    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        echo "Creating pull request, attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
        PR_URL=$(gh pr create \
            --title "$PR_TITLE" \
            --body-file /tmp/pr_body.md \
            --base main \
            --head "$BRANCH_NAME" 2>&1)
        CREATE_EXIT=$?
        if [ $CREATE_EXIT -eq 0 ]; then
            echo "Pull Request created: $PR_URL"
            PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
            break
        fi
        RETRY_COUNT=$((RETRY_COUNT + 1))
        if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
            echo "PR creation failed — retrying in 30 seconds..."
            echo "Error output: $PR_URL"
            sleep 30
            EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number' 2>/dev/null || echo "")
            if [ -n "$EXISTING_PR" ]; then
                echo "PR appeared after retry check: #$EXISTING_PR"
                PR_NUMBER="$EXISTING_PR"
                break
            fi
        else
            echo "Failed to create PR after $MAX_RETRIES attempts"
            echo "Last error: $PR_URL"
            exit 1
        fi
    done
fi

echo "PR_NUMBER=${PR_NUMBER}" >> "$GITHUB_ENV"
